"use client";

import { useMemo, useState } from "react";
import { CheckCircle2, Loader2, RotateCcw, Save, Shuffle, UserCheck, Users, type LucideIcon } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toast } from "@/hooks/use-toast";
import { cn, formatDate } from "@/lib/utils";
import type { AppUser, CustomerSummary, Locale } from "@/types/crm";

type Rule = "balanced" | "country" | "grade";

const copy = {
  zh: {
    title: "自动分配销售",
    subtitle: "按国家、客户等级和销售负载，把新客户分配给合适业务员。",
    unassigned: "未分配客户",
    availableSales: "可用销售",
    assigned: "已分配",
    avgLoad: "平均负载",
    country: "按国家匹配",
    balanced: "按负载均衡",
    grade: "A级客户优先",
    autoAssign: "自动分配",
    save: "保存分配",
    reset: "重置",
    customer: "客户",
    countryHeader: "国家",
    source: "来源",
    gradeHeader: "等级",
    lastContact: "最近联系",
    salesOwner: "负责销售",
    load: "负载",
    won: "已成交客户",
    focus: "负责市场",
    saved: "销售分配已保存",
    autoDone: "已按规则完成分配",
    empty: "暂无可分配客户",
    noSales: "请先在 Supabase 用户表中创建 Sales 角色用户"
  },
  en: {
    title: "Auto Assign Sales",
    subtitle: "Assign customers to the right salesperson by country, grade, and workload.",
    unassigned: "Unassigned customers",
    availableSales: "Available sales",
    assigned: "Assigned",
    avgLoad: "Average load",
    country: "Match country",
    balanced: "Balance workload",
    grade: "Prioritize A grade",
    autoAssign: "Auto assign",
    save: "Save assignments",
    reset: "Reset",
    customer: "Customer",
    countryHeader: "Country",
    source: "Source",
    gradeHeader: "Grade",
    lastContact: "Last contact",
    salesOwner: "Sales owner",
    load: "Load",
    won: "Won customers",
    focus: "Markets",
    saved: "Sales assignments saved",
    autoDone: "Assignments generated by rule",
    empty: "No customers to assign",
    noSales: "Create users with the Sales role in Supabase first"
  },
  id: {
    title: "Auto Assign Sales",
    subtitle: "Assign pelanggan ke sales yang tepat berdasarkan negara, grade, dan workload.",
    unassigned: "Pelanggan belum assign",
    availableSales: "Sales tersedia",
    assigned: "Sudah assign",
    avgLoad: "Rata-rata load",
    country: "Cocokkan negara",
    balanced: "Seimbangkan workload",
    grade: "Prioritaskan grade A",
    autoAssign: "Auto assign",
    save: "Simpan assignment",
    reset: "Reset",
    customer: "Pelanggan",
    countryHeader: "Negara",
    source: "Sumber",
    gradeHeader: "Grade",
    lastContact: "Kontak terakhir",
    salesOwner: "Owner sales",
    load: "Load",
    won: "Customer won",
    focus: "Market",
    saved: "Assignment sales disimpan",
    autoDone: "Assignment dibuat sesuai aturan",
    empty: "Tidak ada pelanggan untuk assign",
    noSales: "Buat user dengan role Sales di Supabase terlebih dahulu"
  }
} as const;

export function SalesAssignmentWorkspace({
  locale,
  customers,
  salesUsers
}: {
  locale: Locale;
  customers: CustomerSummary[];
  salesUsers: AppUser[];
}) {
  const page = copy[locale];
  const candidates = useMemo(() => customers.filter((customer) => customer.stage !== "won").slice(0, 12), [customers]);
  const initialAssignments = useMemo(
    () => Object.fromEntries(candidates.map((customer) => [customer.id, customer.owner_id ?? "unassigned"])),
    [candidates]
  );
  const [assignments, setAssignments] = useState<Record<string, string>>(initialAssignments);
  const [rule, setRule] = useState<Rule>("country");
  const [saving, setSaving] = useState(false);

  const assignedCount = Object.values(assignments).filter((value) => value !== "unassigned").length;
  const repLoad = useMemo(
    () =>
      salesUsers.map((rep) => {
        const ownedCustomers = customers.filter((customer) => customer.owner_id === rep.id);
        const pending = Object.values(assignments).filter((salesId) => salesId === rep.id).length;
        const markets = Array.from(new Set(ownedCustomers.map((customer) => customer.country).filter(Boolean) as string[]));
        return {
          ...rep,
          name: rep.full_name ?? rep.email ?? rep.id,
          activeCustomers: ownedCustomers.length,
          wonCustomers: ownedCustomers.filter((customer) => customer.stage === "won").length,
          pending,
          markets
        };
      }),
    [assignments, customers, salesUsers]
  );
  const averageLoad = repLoad.length
    ? Math.round(repLoad.reduce((sum, rep) => sum + rep.activeCustomers + rep.pending, 0) / repLoad.length)
    : 0;

  function autoAssign() {
    if (!repLoad.length) {
      toast({ title: page.noSales, variant: "destructive" });
      return;
    }

    const next: Record<string, string> = {};
    const load = Object.fromEntries(repLoad.map((rep) => [rep.id, rep.activeCustomers]));
    const sortedCustomers = [...candidates].sort((a, b) => {
      if (rule !== "grade") return 0;
      return gradeScore(b.grade) - gradeScore(a.grade);
    });

    for (const customer of sortedCustomers) {
      const countryPool =
        rule === "country" ? repLoad.filter((rep) => rep.markets.includes(customer.country ?? "")) : [];
      const pool = countryPool.length ? countryPool : repLoad;
      const selected = [...pool].sort((a, b) => load[a.id] - load[b.id])[0];
      next[customer.id] = selected.id;
      load[selected.id] += 1;
    }

    setAssignments(next);
    toast({ title: page.autoDone });
  }

  async function saveAssignments() {
    const rows = candidates
      .map((customer) => {
        const rep = repLoad.find((item) => item.id === assignments[customer.id]);
        return rep ? { customer_id: customer.id, sales_id: rep.id, sales_name: rep.name } : null;
      })
      .filter((row): row is { customer_id: string; sales_id: string; sales_name: string } => Boolean(row));

    if (!rows.length) return;
    setSaving(true);
    const response = await fetch("/api/sales-assignment/assign", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ assignments: rows })
    });
    const payload = await response.json().catch(() => null);
    setSaving(false);

    if (!response.ok) {
      toast({ title: "Save failed", description: payload?.error, variant: "destructive" });
      return;
    }

    toast({ title: page.saved });
  }

  return (
    <div className="space-y-5">
      <div className="grid gap-4 md:grid-cols-4">
        <MetricCard icon={Users} label={page.unassigned} value={String(Math.max(candidates.length - assignedCount, 0))} />
        <MetricCard icon={UserCheck} label={page.availableSales} value={String(salesUsers.length)} />
        <MetricCard icon={CheckCircle2} label={page.assigned} value={String(assignedCount)} />
        <MetricCard icon={Shuffle} label={page.avgLoad} value={String(averageLoad)} />
      </div>

      <div className="grid gap-5 xl:grid-cols-[1fr_360px]">
        <Card>
          <CardHeader className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
            <div>
              <CardTitle>{page.title}</CardTitle>
              <p className="mt-1 text-sm text-muted-foreground">{page.subtitle}</p>
            </div>
            <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
              <Select value={rule} onValueChange={(value) => setRule(value as Rule)}>
                <SelectTrigger className="w-full sm:w-44">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="country">{page.country}</SelectItem>
                  <SelectItem value="balanced">{page.balanced}</SelectItem>
                  <SelectItem value="grade">{page.grade}</SelectItem>
                </SelectContent>
              </Select>
              <Button type="button" variant="outline" onClick={() => setAssignments(initialAssignments)}>
                <RotateCcw className="size-4" />
                {page.reset}
              </Button>
              <Button type="button" onClick={autoAssign} disabled={!salesUsers.length}>
                <Shuffle className="size-4" />
                {page.autoAssign}
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>{page.customer}</TableHead>
                  <TableHead>{page.countryHeader}</TableHead>
                  <TableHead>{page.source}</TableHead>
                  <TableHead>{page.gradeHeader}</TableHead>
                  <TableHead>{page.lastContact}</TableHead>
                  <TableHead className="min-w-48">{page.salesOwner}</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {candidates.length ? (
                  candidates.map((customer) => (
                    <TableRow key={customer.id}>
                      <TableCell>
                        <div>
                          <p className="font-medium">{customer.company_name}</p>
                          <p className="text-xs text-muted-foreground">{customer.contact_name ?? "-"}</p>
                        </div>
                      </TableCell>
                      <TableCell>{customer.country ?? "-"}</TableCell>
                      <TableCell>{customer.source ?? "-"}</TableCell>
                      <TableCell>
                        <Badge variant={customer.grade === "A" ? "success" : "secondary"}>{customer.grade}</Badge>
                      </TableCell>
                      <TableCell>{formatDate(customer.last_contacted_at, "yyyy-MM-dd", locale)}</TableCell>
                      <TableCell>
                        <Select
                          value={assignments[customer.id] ?? "unassigned"}
                          onValueChange={(value) => setAssignments((current) => ({ ...current, [customer.id]: value }))}
                          disabled={!salesUsers.length}
                        >
                          <SelectTrigger>
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="unassigned">Unassigned</SelectItem>
                            {repLoad.map((rep) => (
                              <SelectItem key={rep.id} value={rep.id}>
                                {rep.name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </TableCell>
                    </TableRow>
                  ))
                ) : (
                  <TableRow>
                    <TableCell colSpan={6} className="h-24 text-center text-muted-foreground">
                      {page.empty}
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>

            <div className="mt-4 flex justify-end">
              <Button type="button" onClick={saveAssignments} disabled={saving || assignedCount === 0}>
                {saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}
                {page.save}
              </Button>
            </div>
          </CardContent>
        </Card>

        <aside className="space-y-4">
          {repLoad.length ? (
            repLoad.map((rep) => {
              const load = rep.activeCustomers + rep.pending;
              return (
                <Card key={rep.id}>
                  <CardContent className="p-4">
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <p className="font-semibold">{rep.name}</p>
                        <p className="mt-1 text-xs text-muted-foreground">{rep.email ?? rep.role}</p>
                      </div>
                      <Badge variant={rep.pending ? "success" : "secondary"}>+{rep.pending}</Badge>
                    </div>
                    <div className="mt-4 space-y-3">
                      <ProgressLine label={`${page.load}: ${load}`} value={Math.min(100, load * 4)} />
                      <div className="grid gap-1 text-xs text-muted-foreground">
                        <span>{page.won}: {rep.wonCustomers}</span>
                        <span>{page.focus}: {rep.markets.length ? rep.markets.join(", ") : "-"}</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              );
            })
          ) : (
            <Card>
              <CardContent className="p-4 text-sm text-muted-foreground">{page.noSales}</CardContent>
            </Card>
          )}
        </aside>
      </div>
    </div>
  );
}

function MetricCard({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string }) {
  return (
    <Card>
      <CardContent className="flex items-center justify-between gap-3 p-4">
        <div>
          <p className="text-sm text-muted-foreground">{label}</p>
          <p className="mt-2 text-2xl font-semibold">{value}</p>
        </div>
        <span className="flex size-10 items-center justify-center rounded-md bg-primary/10 text-primary">
          <Icon className="size-5" />
        </span>
      </CardContent>
    </Card>
  );
}

function ProgressLine({ label, value }: { label: string; value: number }) {
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-xs text-muted-foreground">
        <span>{label}</span>
      </div>
      <div className="h-2 rounded-full bg-muted">
        <div className={cn("h-2 rounded-full bg-primary transition-all", value > 85 && "bg-amber-500")} style={{ width: `${value}%` }} />
      </div>
    </div>
  );
}

function gradeScore(grade: CustomerSummary["grade"]) {
  if (grade === "A") return 3;
  if (grade === "B") return 2;
  return 1;
}
